### ISSUE TITLE
broken things after redesign

### ISSUE THREAD

**Issue by pishifat** [pishifat/mappersguild2#18]
- [ ] ![](https://i.imgur.com/Do4Zo8t.png) same on many buttons with icons elsewhere
- [ ] filterbox buttons dont do anything on beatmaps ![](https://i.imgur.com/E6jzpXQ.png)
- [ ] all the host options are gone from map modal (change status, delete diffs, change link, etc)
- [ ] ![](https://i.imgur.com/64WxC5L.png) no status indicators for diffs? they wrok on /showcase so bug?
- [ ] ![](https://i.imgur.com/cTtF8OI.png) when trying to do anything on a map. only affects client side
- [ ] ![](https://i.imgur.com/62DRDyU.png) highlighting looks weird on these. make it full highlight box like quests?
- [ ] ![](https://i.imgur.com/XYoBxsA.png) when adding new map
- [ ] ![](https://i.imgur.com/m0Bna5U.png) should save "leave" when in party
- [ ] quest leader options are gone (cant accept quest, kick members, etc)
- [ ] mode filters are missing on quests
- [ ] user cards kinda ugly because 3 horizontal bars, would be fixed if it looked like /qat's user things (faded triangles from side)
- [ ] ![](https://i.imgur.com/ClHu7L8.png) ugly
- [ ] ![](https://i.imgur.com/SFTjDss.png) x needs red
- [ ] show loading on artists and all admin pages (including screening/judging) otherwise everyhitng is 0/"none" for a while
- [ ] ![](https://i.imgur.com/oSJygni.png) is this intentional? on screening when clicking a star
- [ ] judging page doesnt work
- [ ] seeing lots of console errors when switching between pages too quickly. like if i go to admin/users before admin/featuredartists loads data, i get this error ![](https://i.imgur.com/o8W8p5Q.png)
- [ ] quests admin has lots of console errors, doesn't seem to affect functionality though (all warnings)

didnt check things with notifications because theyre so annoying to set up, but ill do that next pass

**Comment by milaneyia** [comment]
> seeing lots of console errors when switching between pages too quickly. like if i go to admin/users before admin/featuredartists loads data, i get this error

cant really fix this now since stores are being unregistered before the api call finishes. may become irrelevant once vuex stuff is more cleaned up

> judging page doesnt work

it works for me after changing the last contest status (?

rest is fixed
